// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGES_NPLEX_MSGS_H_
#define FLATBUFFERS_GENERATED_MESSAGES_NPLEX_MSGS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace nplex {
namespace msgs {

struct KeyValue;
struct KeyValueBuilder;
struct KeyValueT;

struct Transaction;
struct TransactionBuilder;
struct TransactionT;

struct Snapshot;
struct SnapshotBuilder;
struct SnapshotT;

struct Check;
struct CheckBuilder;
struct CheckT;

struct LoginRequest;
struct LoginRequestBuilder;
struct LoginRequestT;

struct LoginResponse;
struct LoginResponseBuilder;
struct LoginResponseT;

struct PingRequest;
struct PingRequestBuilder;
struct PingRequestT;

struct PingResponse;
struct PingResponseBuilder;
struct PingResponseT;

struct LoadRequest;
struct LoadRequestBuilder;
struct LoadRequestT;

struct LoadResponse;
struct LoadResponseBuilder;
struct LoadResponseT;

struct CommitResponse;
struct CommitResponseBuilder;
struct CommitResponseT;

struct SubmitRequest;
struct SubmitRequestBuilder;
struct SubmitRequestT;

struct SubmitResponse;
struct SubmitResponseBuilder;
struct SubmitResponseT;

struct KeepAliveRequest;
struct KeepAliveRequestBuilder;
struct KeepAliveRequestT;

enum class LoginCode : int8_t {
  UNKNOW = 0,
  AUTHORIZED = 1,
  INVALID_CREDENTIALS = 2,
  COMPAT_MISMATCH = 3,
  ALREADY_LOGGED = 4,
  NOT_LEADER = 5,
  DBID_MISMATCH = 6,
  MIN = UNKNOW,
  MAX = DBID_MISMATCH
};

inline const LoginCode (&EnumValuesLoginCode())[7] {
  static const LoginCode values[] = {
    LoginCode::UNKNOW,
    LoginCode::AUTHORIZED,
    LoginCode::INVALID_CREDENTIALS,
    LoginCode::COMPAT_MISMATCH,
    LoginCode::ALREADY_LOGGED,
    LoginCode::NOT_LEADER,
    LoginCode::DBID_MISMATCH
  };
  return values;
}

inline const char * const *EnumNamesLoginCode() {
  static const char * const names[8] = {
    "UNKNOW",
    "AUTHORIZED",
    "INVALID_CREDENTIALS",
    "COMPAT_MISMATCH",
    "ALREADY_LOGGED",
    "NOT_LEADER",
    "DBID_MISMATCH",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoginCode(LoginCode e) {
  if (::flatbuffers::IsOutRange(e, LoginCode::UNKNOW, LoginCode::DBID_MISMATCH)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoginCode()[index];
}

enum class LoadMode : int8_t {
  UNKNOW = 0,
  SNAPSHOT_AT_FIXED_REV = 1,
  SNAPSHOT_AT_LAST_REV = 2,
  ONLY_UPDATES_FROM_REV = 3,
  MIN = UNKNOW,
  MAX = ONLY_UPDATES_FROM_REV
};

inline const LoadMode (&EnumValuesLoadMode())[4] {
  static const LoadMode values[] = {
    LoadMode::UNKNOW,
    LoadMode::SNAPSHOT_AT_FIXED_REV,
    LoadMode::SNAPSHOT_AT_LAST_REV,
    LoadMode::ONLY_UPDATES_FROM_REV
  };
  return values;
}

inline const char * const *EnumNamesLoadMode() {
  static const char * const names[5] = {
    "UNKNOW",
    "SNAPSHOT_AT_FIXED_REV",
    "SNAPSHOT_AT_LAST_REV",
    "ONLY_UPDATES_FROM_REV",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoadMode(LoadMode e) {
  if (::flatbuffers::IsOutRange(e, LoadMode::UNKNOW, LoadMode::ONLY_UPDATES_FROM_REV)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoadMode()[index];
}

struct KeyValueT : public ::flatbuffers::NativeTable {
  typedef KeyValue TableType;
  std::string key{};
  std::vector<uint8_t> value{};
};

struct KeyValue FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyValueT NativeTableType;
  typedef KeyValueBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::Vector<uint8_t> *value() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyVector(value()) &&
           verifier.EndTable();
  }
  KeyValueT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(KeyValueT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<KeyValue> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const KeyValueT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct KeyValueBuilder {
  typedef KeyValue Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(KeyValue::VT_KEY, key);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> value) {
    fbb_.AddOffset(KeyValue::VT_VALUE, value);
  }
  explicit KeyValueBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyValue> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyValue>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyValue> CreateKeyValue(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> value = 0) {
  KeyValueBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

struct KeyValue::Traits {
  using type = KeyValue;
  static auto constexpr Create = CreateKeyValue;
};

inline ::flatbuffers::Offset<KeyValue> CreateKeyValueDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const std::vector<uint8_t> *value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto value__ = value ? _fbb.CreateVector<uint8_t>(*value) : 0;
  return nplex::msgs::CreateKeyValue(
      _fbb,
      key__,
      value__);
}

::flatbuffers::Offset<KeyValue> CreateKeyValue(::flatbuffers::FlatBufferBuilder &_fbb, const KeyValueT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TransactionT : public ::flatbuffers::NativeTable {
  typedef Transaction TableType;
  uint64_t rev = 0;
  std::string user{};
  uint64_t timestamp = 0;
  uint32_t type = 0;
  std::vector<std::unique_ptr<nplex::msgs::KeyValueT>> upserts{};
  std::vector<std::string> deletes{};
  TransactionT() = default;
  TransactionT(const TransactionT &o);
  TransactionT(TransactionT&&) FLATBUFFERS_NOEXCEPT = default;
  TransactionT &operator=(TransactionT o) FLATBUFFERS_NOEXCEPT;
};

struct Transaction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransactionT NativeTableType;
  typedef TransactionBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REV = 4,
    VT_USER = 6,
    VT_TIMESTAMP = 8,
    VT_TYPE = 10,
    VT_UPSERTS = 12,
    VT_DELETES = 14
  };
  uint64_t rev() const {
    return GetField<uint64_t>(VT_REV, 0);
  }
  const ::flatbuffers::String *user() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USER);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint32_t type() const {
    return GetField<uint32_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *>(VT_UPSERTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DELETES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_REV, 8) &&
           VerifyOffset(verifier, VT_USER) &&
           verifier.VerifyString(user()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_UPSERTS) &&
           verifier.VerifyVector(upserts()) &&
           verifier.VerifyVectorOfTables(upserts()) &&
           VerifyOffset(verifier, VT_DELETES) &&
           verifier.VerifyVector(deletes()) &&
           verifier.VerifyVectorOfStrings(deletes()) &&
           verifier.EndTable();
  }
  TransactionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TransactionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Transaction> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TransactionBuilder {
  typedef Transaction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rev(uint64_t rev) {
    fbb_.AddElement<uint64_t>(Transaction::VT_REV, rev, 0);
  }
  void add_user(::flatbuffers::Offset<::flatbuffers::String> user) {
    fbb_.AddOffset(Transaction::VT_USER, user);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Transaction::VT_TIMESTAMP, timestamp, 0);
  }
  void add_type(uint32_t type) {
    fbb_.AddElement<uint32_t>(Transaction::VT_TYPE, type, 0);
  }
  void add_upserts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts) {
    fbb_.AddOffset(Transaction::VT_UPSERTS, upserts);
  }
  void add_deletes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes) {
    fbb_.AddOffset(Transaction::VT_DELETES, deletes);
  }
  explicit TransactionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Transaction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Transaction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Transaction> CreateTransaction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    ::flatbuffers::Offset<::flatbuffers::String> user = 0,
    uint64_t timestamp = 0,
    uint32_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes = 0) {
  TransactionBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_rev(rev);
  builder_.add_deletes(deletes);
  builder_.add_upserts(upserts);
  builder_.add_type(type);
  builder_.add_user(user);
  return builder_.Finish();
}

struct Transaction::Traits {
  using type = Transaction;
  static auto constexpr Create = CreateTransaction;
};

inline ::flatbuffers::Offset<Transaction> CreateTransactionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    const char *user = nullptr,
    uint64_t timestamp = 0,
    uint32_t type = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes = nullptr) {
  auto user__ = user ? _fbb.CreateString(user) : 0;
  auto upserts__ = upserts ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::KeyValue>>(*upserts) : 0;
  auto deletes__ = deletes ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*deletes) : 0;
  return nplex::msgs::CreateTransaction(
      _fbb,
      rev,
      user__,
      timestamp,
      type,
      upserts__,
      deletes__);
}

::flatbuffers::Offset<Transaction> CreateTransaction(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SnapshotT : public ::flatbuffers::NativeTable {
  typedef Snapshot TableType;
  uint64_t rev = 0;
  std::vector<std::unique_ptr<nplex::msgs::TransactionT>> transactions{};
  SnapshotT() = default;
  SnapshotT(const SnapshotT &o);
  SnapshotT(SnapshotT&&) FLATBUFFERS_NOEXCEPT = default;
  SnapshotT &operator=(SnapshotT o) FLATBUFFERS_NOEXCEPT;
};

struct Snapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SnapshotT NativeTableType;
  typedef SnapshotBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REV = 4,
    VT_TRANSACTIONS = 6
  };
  uint64_t rev() const {
    return GetField<uint64_t>(VT_REV, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Transaction>> *transactions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Transaction>> *>(VT_TRANSACTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_REV, 8) &&
           VerifyOffset(verifier, VT_TRANSACTIONS) &&
           verifier.VerifyVector(transactions()) &&
           verifier.VerifyVectorOfTables(transactions()) &&
           verifier.EndTable();
  }
  SnapshotT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SnapshotT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Snapshot> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SnapshotBuilder {
  typedef Snapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_rev(uint64_t rev) {
    fbb_.AddElement<uint64_t>(Snapshot::VT_REV, rev, 0);
  }
  void add_transactions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Transaction>>> transactions) {
    fbb_.AddOffset(Snapshot::VT_TRANSACTIONS, transactions);
  }
  explicit SnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Snapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Snapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Snapshot> CreateSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Transaction>>> transactions = 0) {
  SnapshotBuilder builder_(_fbb);
  builder_.add_rev(rev);
  builder_.add_transactions(transactions);
  return builder_.Finish();
}

struct Snapshot::Traits {
  using type = Snapshot;
  static auto constexpr Create = CreateSnapshot;
};

inline ::flatbuffers::Offset<Snapshot> CreateSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t rev = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::Transaction>> *transactions = nullptr) {
  auto transactions__ = transactions ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::Transaction>>(*transactions) : 0;
  return nplex::msgs::CreateSnapshot(
      _fbb,
      rev,
      transactions__);
}

::flatbuffers::Offset<Snapshot> CreateSnapshot(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CheckT : public ::flatbuffers::NativeTable {
  typedef Check TableType;
  std::string pattern{};
  uint8_t mode = 0;
};

struct Check FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CheckT NativeTableType;
  typedef CheckBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATTERN = 4,
    VT_MODE = 6
  };
  const ::flatbuffers::String *pattern() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATTERN);
  }
  uint8_t mode() const {
    return GetField<uint8_t>(VT_MODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATTERN) &&
           verifier.VerifyString(pattern()) &&
           VerifyField<uint8_t>(verifier, VT_MODE, 1) &&
           verifier.EndTable();
  }
  CheckT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CheckT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Check> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CheckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CheckBuilder {
  typedef Check Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pattern(::flatbuffers::Offset<::flatbuffers::String> pattern) {
    fbb_.AddOffset(Check::VT_PATTERN, pattern);
  }
  void add_mode(uint8_t mode) {
    fbb_.AddElement<uint8_t>(Check::VT_MODE, mode, 0);
  }
  explicit CheckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Check> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Check>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Check> CreateCheck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> pattern = 0,
    uint8_t mode = 0) {
  CheckBuilder builder_(_fbb);
  builder_.add_pattern(pattern);
  builder_.add_mode(mode);
  return builder_.Finish();
}

struct Check::Traits {
  using type = Check;
  static auto constexpr Create = CreateCheck;
};

inline ::flatbuffers::Offset<Check> CreateCheckDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *pattern = nullptr,
    uint8_t mode = 0) {
  auto pattern__ = pattern ? _fbb.CreateString(pattern) : 0;
  return nplex::msgs::CreateCheck(
      _fbb,
      pattern__,
      mode);
}

::flatbuffers::Offset<Check> CreateCheck(::flatbuffers::FlatBufferBuilder &_fbb, const CheckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct LoginRequestT : public ::flatbuffers::NativeTable {
  typedef LoginRequest TableType;
  uint64_t cid = 0;
  std::string user{};
  std::string password{};
};

struct LoginRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginRequestT NativeTableType;
  typedef LoginRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_USER = 6,
    VT_PASSWORD = 8
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  const ::flatbuffers::String *user() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USER);
  }
  const ::flatbuffers::String *password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASSWORD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyOffset(verifier, VT_USER) &&
           verifier.VerifyString(user()) &&
           VerifyOffset(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           verifier.EndTable();
  }
  LoginRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LoginRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LoginRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoginRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LoginRequestBuilder {
  typedef LoginRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoginRequest::VT_CID, cid, 0);
  }
  void add_user(::flatbuffers::Offset<::flatbuffers::String> user) {
    fbb_.AddOffset(LoginRequest::VT_USER, user);
  }
  void add_password(::flatbuffers::Offset<::flatbuffers::String> password) {
    fbb_.AddOffset(LoginRequest::VT_PASSWORD, password);
  }
  explicit LoginRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginRequest> CreateLoginRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> user = 0,
    ::flatbuffers::Offset<::flatbuffers::String> password = 0) {
  LoginRequestBuilder builder_(_fbb);
  builder_.add_cid(cid);
  builder_.add_password(password);
  builder_.add_user(user);
  return builder_.Finish();
}

struct LoginRequest::Traits {
  using type = LoginRequest;
  static auto constexpr Create = CreateLoginRequest;
};

inline ::flatbuffers::Offset<LoginRequest> CreateLoginRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    const char *user = nullptr,
    const char *password = nullptr) {
  auto user__ = user ? _fbb.CreateString(user) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  return nplex::msgs::CreateLoginRequest(
      _fbb,
      cid,
      user__,
      password__);
}

::flatbuffers::Offset<LoginRequest> CreateLoginRequest(::flatbuffers::FlatBufferBuilder &_fbb, const LoginRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct LoginResponseT : public ::flatbuffers::NativeTable {
  typedef LoginResponse TableType;
  uint64_t cid = 0;
  nplex::msgs::LoginCode code = nplex::msgs::LoginCode::UNKNOW;
  std::string session{};
  uint64_t rev0 = 0;
  uint64_t crev = 0;
};

struct LoginResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginResponseT NativeTableType;
  typedef LoginResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CODE = 6,
    VT_SESSION = 8,
    VT_REV0 = 10,
    VT_CREV = 12
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  nplex::msgs::LoginCode code() const {
    return static_cast<nplex::msgs::LoginCode>(GetField<int8_t>(VT_CODE, 0));
  }
  const ::flatbuffers::String *session() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SESSION);
  }
  uint64_t rev0() const {
    return GetField<uint64_t>(VT_REV0, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<int8_t>(verifier, VT_CODE, 1) &&
           VerifyOffset(verifier, VT_SESSION) &&
           verifier.VerifyString(session()) &&
           VerifyField<uint64_t>(verifier, VT_REV0, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           verifier.EndTable();
  }
  LoginResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LoginResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LoginResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoginResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LoginResponseBuilder {
  typedef LoginResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoginResponse::VT_CID, cid, 0);
  }
  void add_code(nplex::msgs::LoginCode code) {
    fbb_.AddElement<int8_t>(LoginResponse::VT_CODE, static_cast<int8_t>(code), 0);
  }
  void add_session(::flatbuffers::Offset<::flatbuffers::String> session) {
    fbb_.AddOffset(LoginResponse::VT_SESSION, session);
  }
  void add_rev0(uint64_t rev0) {
    fbb_.AddElement<uint64_t>(LoginResponse::VT_REV0, rev0, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(LoginResponse::VT_CREV, crev, 0);
  }
  explicit LoginResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginResponse> CreateLoginResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    nplex::msgs::LoginCode code = nplex::msgs::LoginCode::UNKNOW,
    ::flatbuffers::Offset<::flatbuffers::String> session = 0,
    uint64_t rev0 = 0,
    uint64_t crev = 0) {
  LoginResponseBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_rev0(rev0);
  builder_.add_cid(cid);
  builder_.add_session(session);
  builder_.add_code(code);
  return builder_.Finish();
}

struct LoginResponse::Traits {
  using type = LoginResponse;
  static auto constexpr Create = CreateLoginResponse;
};

inline ::flatbuffers::Offset<LoginResponse> CreateLoginResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    nplex::msgs::LoginCode code = nplex::msgs::LoginCode::UNKNOW,
    const char *session = nullptr,
    uint64_t rev0 = 0,
    uint64_t crev = 0) {
  auto session__ = session ? _fbb.CreateString(session) : 0;
  return nplex::msgs::CreateLoginResponse(
      _fbb,
      cid,
      code,
      session__,
      rev0,
      crev);
}

::flatbuffers::Offset<LoginResponse> CreateLoginResponse(::flatbuffers::FlatBufferBuilder &_fbb, const LoginResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PingRequestT : public ::flatbuffers::NativeTable {
  typedef PingRequest TableType;
  uint64_t cid = 0;
  std::string payload{};
};

struct PingRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PingRequestT NativeTableType;
  typedef PingRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_PAYLOAD = 6
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  const ::flatbuffers::String *payload() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           verifier.EndTable();
  }
  PingRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PingRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PingRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PingRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PingRequestBuilder {
  typedef PingRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(PingRequest::VT_CID, cid, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::String> payload) {
    fbb_.AddOffset(PingRequest::VT_PAYLOAD, payload);
  }
  explicit PingRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PingRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PingRequest> CreatePingRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> payload = 0) {
  PingRequestBuilder builder_(_fbb);
  builder_.add_cid(cid);
  builder_.add_payload(payload);
  return builder_.Finish();
}

struct PingRequest::Traits {
  using type = PingRequest;
  static auto constexpr Create = CreatePingRequest;
};

inline ::flatbuffers::Offset<PingRequest> CreatePingRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    const char *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  return nplex::msgs::CreatePingRequest(
      _fbb,
      cid,
      payload__);
}

::flatbuffers::Offset<PingRequest> CreatePingRequest(::flatbuffers::FlatBufferBuilder &_fbb, const PingRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PingResponseT : public ::flatbuffers::NativeTable {
  typedef PingResponse TableType;
  uint64_t crev = 0;
  uint64_t cid = 0;
  std::string payload{};
};

struct PingResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PingResponseT NativeTableType;
  typedef PingResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CREV = 4,
    VT_CID = 6,
    VT_PAYLOAD = 8
  };
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  const ::flatbuffers::String *payload() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyString(payload()) &&
           verifier.EndTable();
  }
  PingResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PingResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PingResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PingResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PingResponseBuilder {
  typedef PingResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(PingResponse::VT_CREV, crev, 0);
  }
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(PingResponse::VT_CID, cid, 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::String> payload) {
    fbb_.AddOffset(PingResponse::VT_PAYLOAD, payload);
  }
  explicit PingResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PingResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PingResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PingResponse> CreatePingResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t crev = 0,
    uint64_t cid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> payload = 0) {
  PingResponseBuilder builder_(_fbb);
  builder_.add_cid(cid);
  builder_.add_crev(crev);
  builder_.add_payload(payload);
  return builder_.Finish();
}

struct PingResponse::Traits {
  using type = PingResponse;
  static auto constexpr Create = CreatePingResponse;
};

inline ::flatbuffers::Offset<PingResponse> CreatePingResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t crev = 0,
    uint64_t cid = 0,
    const char *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateString(payload) : 0;
  return nplex::msgs::CreatePingResponse(
      _fbb,
      crev,
      cid,
      payload__);
}

::flatbuffers::Offset<PingResponse> CreatePingResponse(::flatbuffers::FlatBufferBuilder &_fbb, const PingResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct LoadRequestT : public ::flatbuffers::NativeTable {
  typedef LoadRequest TableType;
  uint64_t cid = 0;
  nplex::msgs::LoadMode mode = nplex::msgs::LoadMode::UNKNOW;
  uint64_t rev = 0;
};

struct LoadRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoadRequestT NativeTableType;
  typedef LoadRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_MODE = 6,
    VT_REV = 8
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  nplex::msgs::LoadMode mode() const {
    return static_cast<nplex::msgs::LoadMode>(GetField<int8_t>(VT_MODE, 0));
  }
  uint64_t rev() const {
    return GetField<uint64_t>(VT_REV, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<int8_t>(verifier, VT_MODE, 1) &&
           VerifyField<uint64_t>(verifier, VT_REV, 8) &&
           verifier.EndTable();
  }
  LoadRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LoadRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LoadRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoadRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LoadRequestBuilder {
  typedef LoadRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoadRequest::VT_CID, cid, 0);
  }
  void add_mode(nplex::msgs::LoadMode mode) {
    fbb_.AddElement<int8_t>(LoadRequest::VT_MODE, static_cast<int8_t>(mode), 0);
  }
  void add_rev(uint64_t rev) {
    fbb_.AddElement<uint64_t>(LoadRequest::VT_REV, rev, 0);
  }
  explicit LoadRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoadRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoadRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoadRequest> CreateLoadRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    nplex::msgs::LoadMode mode = nplex::msgs::LoadMode::UNKNOW,
    uint64_t rev = 0) {
  LoadRequestBuilder builder_(_fbb);
  builder_.add_rev(rev);
  builder_.add_cid(cid);
  builder_.add_mode(mode);
  return builder_.Finish();
}

struct LoadRequest::Traits {
  using type = LoadRequest;
  static auto constexpr Create = CreateLoadRequest;
};

::flatbuffers::Offset<LoadRequest> CreateLoadRequest(::flatbuffers::FlatBufferBuilder &_fbb, const LoadRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct LoadResponseT : public ::flatbuffers::NativeTable {
  typedef LoadResponse TableType;
  uint64_t cid = 0;
  uint64_t crev = 0;
  bool accepted = false;
  std::unique_ptr<nplex::msgs::SnapshotT> snapshot{};
  LoadResponseT() = default;
  LoadResponseT(const LoadResponseT &o);
  LoadResponseT(LoadResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  LoadResponseT &operator=(LoadResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct LoadResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoadResponseT NativeTableType;
  typedef LoadResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_ACCEPTED = 8,
    VT_SNAPSHOT = 10
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  bool accepted() const {
    return GetField<uint8_t>(VT_ACCEPTED, 0) != 0;
  }
  const nplex::msgs::Snapshot *snapshot() const {
    return GetPointer<const nplex::msgs::Snapshot *>(VT_SNAPSHOT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint8_t>(verifier, VT_ACCEPTED, 1) &&
           VerifyOffset(verifier, VT_SNAPSHOT) &&
           verifier.VerifyTable(snapshot()) &&
           verifier.EndTable();
  }
  LoadResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LoadResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<LoadResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoadResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LoadResponseBuilder {
  typedef LoadResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(LoadResponse::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(LoadResponse::VT_CREV, crev, 0);
  }
  void add_accepted(bool accepted) {
    fbb_.AddElement<uint8_t>(LoadResponse::VT_ACCEPTED, static_cast<uint8_t>(accepted), 0);
  }
  void add_snapshot(::flatbuffers::Offset<nplex::msgs::Snapshot> snapshot) {
    fbb_.AddOffset(LoadResponse::VT_SNAPSHOT, snapshot);
  }
  explicit LoadResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoadResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoadResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoadResponse> CreateLoadResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    bool accepted = false,
    ::flatbuffers::Offset<nplex::msgs::Snapshot> snapshot = 0) {
  LoadResponseBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_snapshot(snapshot);
  builder_.add_accepted(accepted);
  return builder_.Finish();
}

struct LoadResponse::Traits {
  using type = LoadResponse;
  static auto constexpr Create = CreateLoadResponse;
};

::flatbuffers::Offset<LoadResponse> CreateLoadResponse(::flatbuffers::FlatBufferBuilder &_fbb, const LoadResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CommitResponseT : public ::flatbuffers::NativeTable {
  typedef CommitResponse TableType;
  uint64_t crev = 0;
  uint64_t cid = 0;
  std::unique_ptr<nplex::msgs::TransactionT> transaction{};
  CommitResponseT() = default;
  CommitResponseT(const CommitResponseT &o);
  CommitResponseT(CommitResponseT&&) FLATBUFFERS_NOEXCEPT = default;
  CommitResponseT &operator=(CommitResponseT o) FLATBUFFERS_NOEXCEPT;
};

struct CommitResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommitResponseT NativeTableType;
  typedef CommitResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CREV = 4,
    VT_CID = 6,
    VT_TRANSACTION = 8
  };
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  const nplex::msgs::Transaction *transaction() const {
    return GetPointer<const nplex::msgs::Transaction *>(VT_TRANSACTION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyOffset(verifier, VT_TRANSACTION) &&
           verifier.VerifyTable(transaction()) &&
           verifier.EndTable();
  }
  CommitResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CommitResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CommitResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommitResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CommitResponseBuilder {
  typedef CommitResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(CommitResponse::VT_CREV, crev, 0);
  }
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(CommitResponse::VT_CID, cid, 0);
  }
  void add_transaction(::flatbuffers::Offset<nplex::msgs::Transaction> transaction) {
    fbb_.AddOffset(CommitResponse::VT_TRANSACTION, transaction);
  }
  explicit CommitResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommitResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommitResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommitResponse> CreateCommitResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t crev = 0,
    uint64_t cid = 0,
    ::flatbuffers::Offset<nplex::msgs::Transaction> transaction = 0) {
  CommitResponseBuilder builder_(_fbb);
  builder_.add_cid(cid);
  builder_.add_crev(crev);
  builder_.add_transaction(transaction);
  return builder_.Finish();
}

struct CommitResponse::Traits {
  using type = CommitResponse;
  static auto constexpr Create = CreateCommitResponse;
};

::flatbuffers::Offset<CommitResponse> CreateCommitResponse(::flatbuffers::FlatBufferBuilder &_fbb, const CommitResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SubmitRequestT : public ::flatbuffers::NativeTable {
  typedef SubmitRequest TableType;
  uint64_t cid = 0;
  uint64_t crev = 0;
  uint32_t type = 0;
  std::vector<std::unique_ptr<nplex::msgs::KeyValueT>> upserts{};
  std::vector<std::string> deletes{};
  std::vector<std::unique_ptr<nplex::msgs::CheckT>> checks{};
  SubmitRequestT() = default;
  SubmitRequestT(const SubmitRequestT &o);
  SubmitRequestT(SubmitRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  SubmitRequestT &operator=(SubmitRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct SubmitRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubmitRequestT NativeTableType;
  typedef SubmitRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_TYPE = 8,
    VT_UPSERTS = 10,
    VT_DELETES = 12,
    VT_CHECKS = 14
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  uint32_t type() const {
    return GetField<uint32_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *>(VT_UPSERTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DELETES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Check>> *checks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Check>> *>(VT_CHECKS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_UPSERTS) &&
           verifier.VerifyVector(upserts()) &&
           verifier.VerifyVectorOfTables(upserts()) &&
           VerifyOffset(verifier, VT_DELETES) &&
           verifier.VerifyVector(deletes()) &&
           verifier.VerifyVectorOfStrings(deletes()) &&
           VerifyOffset(verifier, VT_CHECKS) &&
           verifier.VerifyVector(checks()) &&
           verifier.VerifyVectorOfTables(checks()) &&
           verifier.EndTable();
  }
  SubmitRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SubmitRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SubmitRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SubmitRequestBuilder {
  typedef SubmitRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(SubmitRequest::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(SubmitRequest::VT_CREV, crev, 0);
  }
  void add_type(uint32_t type) {
    fbb_.AddElement<uint32_t>(SubmitRequest::VT_TYPE, type, 0);
  }
  void add_upserts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts) {
    fbb_.AddOffset(SubmitRequest::VT_UPSERTS, upserts);
  }
  void add_deletes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes) {
    fbb_.AddOffset(SubmitRequest::VT_DELETES, deletes);
  }
  void add_checks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Check>>> checks) {
    fbb_.AddOffset(SubmitRequest::VT_CHECKS, checks);
  }
  explicit SubmitRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubmitRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubmitRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubmitRequest> CreateSubmitRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    uint32_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::KeyValue>>> upserts = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> deletes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nplex::msgs::Check>>> checks = 0) {
  SubmitRequestBuilder builder_(_fbb);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_checks(checks);
  builder_.add_deletes(deletes);
  builder_.add_upserts(upserts);
  builder_.add_type(type);
  return builder_.Finish();
}

struct SubmitRequest::Traits {
  using type = SubmitRequest;
  static auto constexpr Create = CreateSubmitRequest;
};

inline ::flatbuffers::Offset<SubmitRequest> CreateSubmitRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    uint32_t type = 0,
    const std::vector<::flatbuffers::Offset<nplex::msgs::KeyValue>> *upserts = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *deletes = nullptr,
    const std::vector<::flatbuffers::Offset<nplex::msgs::Check>> *checks = nullptr) {
  auto upserts__ = upserts ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::KeyValue>>(*upserts) : 0;
  auto deletes__ = deletes ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*deletes) : 0;
  auto checks__ = checks ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::Check>>(*checks) : 0;
  return nplex::msgs::CreateSubmitRequest(
      _fbb,
      cid,
      crev,
      type,
      upserts__,
      deletes__,
      checks__);
}

::flatbuffers::Offset<SubmitRequest> CreateSubmitRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SubmitResponseT : public ::flatbuffers::NativeTable {
  typedef SubmitResponse TableType;
  uint64_t cid = 0;
  uint64_t crev = 0;
  uint64_t erev = 0;
  std::string error{};
};

struct SubmitResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubmitResponseT NativeTableType;
  typedef SubmitResponseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CID = 4,
    VT_CREV = 6,
    VT_EREV = 8,
    VT_ERROR = 10
  };
  uint64_t cid() const {
    return GetField<uint64_t>(VT_CID, 0);
  }
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  uint64_t erev() const {
    return GetField<uint64_t>(VT_EREV, 0);
  }
  const ::flatbuffers::String *error() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CID, 8) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           VerifyField<uint64_t>(verifier, VT_EREV, 8) &&
           VerifyOffset(verifier, VT_ERROR) &&
           verifier.VerifyString(error()) &&
           verifier.EndTable();
  }
  SubmitResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SubmitResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SubmitResponse> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SubmitResponseBuilder {
  typedef SubmitResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cid(uint64_t cid) {
    fbb_.AddElement<uint64_t>(SubmitResponse::VT_CID, cid, 0);
  }
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(SubmitResponse::VT_CREV, crev, 0);
  }
  void add_erev(uint64_t erev) {
    fbb_.AddElement<uint64_t>(SubmitResponse::VT_EREV, erev, 0);
  }
  void add_error(::flatbuffers::Offset<::flatbuffers::String> error) {
    fbb_.AddOffset(SubmitResponse::VT_ERROR, error);
  }
  explicit SubmitResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubmitResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubmitResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubmitResponse> CreateSubmitResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    uint64_t erev = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error = 0) {
  SubmitResponseBuilder builder_(_fbb);
  builder_.add_erev(erev);
  builder_.add_crev(crev);
  builder_.add_cid(cid);
  builder_.add_error(error);
  return builder_.Finish();
}

struct SubmitResponse::Traits {
  using type = SubmitResponse;
  static auto constexpr Create = CreateSubmitResponse;
};

inline ::flatbuffers::Offset<SubmitResponse> CreateSubmitResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t cid = 0,
    uint64_t crev = 0,
    uint64_t erev = 0,
    const char *error = nullptr) {
  auto error__ = error ? _fbb.CreateString(error) : 0;
  return nplex::msgs::CreateSubmitResponse(
      _fbb,
      cid,
      crev,
      erev,
      error__);
}

::flatbuffers::Offset<SubmitResponse> CreateSubmitResponse(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct KeepAliveRequestT : public ::flatbuffers::NativeTable {
  typedef KeepAliveRequest TableType;
  uint64_t crev = 0;
};

struct KeepAliveRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeepAliveRequestT NativeTableType;
  typedef KeepAliveRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CREV = 4
  };
  uint64_t crev() const {
    return GetField<uint64_t>(VT_CREV, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CREV, 8) &&
           verifier.EndTable();
  }
  KeepAliveRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(KeepAliveRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<KeepAliveRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const KeepAliveRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct KeepAliveRequestBuilder {
  typedef KeepAliveRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_crev(uint64_t crev) {
    fbb_.AddElement<uint64_t>(KeepAliveRequest::VT_CREV, crev, 0);
  }
  explicit KeepAliveRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeepAliveRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeepAliveRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeepAliveRequest> CreateKeepAliveRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t crev = 0) {
  KeepAliveRequestBuilder builder_(_fbb);
  builder_.add_crev(crev);
  return builder_.Finish();
}

struct KeepAliveRequest::Traits {
  using type = KeepAliveRequest;
  static auto constexpr Create = CreateKeepAliveRequest;
};

::flatbuffers::Offset<KeepAliveRequest> CreateKeepAliveRequest(::flatbuffers::FlatBufferBuilder &_fbb, const KeepAliveRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline KeyValueT *KeyValue::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<KeyValueT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void KeyValue::UnPackTo(KeyValueT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = key(); if (_e) _o->key = _e->str(); }
  { auto _e = value(); if (_e) { _o->value.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->value.begin()); } }
}

inline ::flatbuffers::Offset<KeyValue> KeyValue::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const KeyValueT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateKeyValue(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<KeyValue> CreateKeyValue(::flatbuffers::FlatBufferBuilder &_fbb, const KeyValueT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const KeyValueT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _key = _o->key.empty() ? 0 : _fbb.CreateString(_o->key);
  auto _value = _o->value.size() ? _fbb.CreateVector(_o->value) : 0;
  return nplex::msgs::CreateKeyValue(
      _fbb,
      _key,
      _value);
}

inline TransactionT::TransactionT(const TransactionT &o)
      : rev(o.rev),
        user(o.user),
        timestamp(o.timestamp),
        type(o.type),
        deletes(o.deletes) {
  upserts.reserve(o.upserts.size());
  for (const auto &upserts_ : o.upserts) { upserts.emplace_back((upserts_) ? new nplex::msgs::KeyValueT(*upserts_) : nullptr); }
}

inline TransactionT &TransactionT::operator=(TransactionT o) FLATBUFFERS_NOEXCEPT {
  std::swap(rev, o.rev);
  std::swap(user, o.user);
  std::swap(timestamp, o.timestamp);
  std::swap(type, o.type);
  std::swap(upserts, o.upserts);
  std::swap(deletes, o.deletes);
  return *this;
}

inline TransactionT *Transaction::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<TransactionT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Transaction::UnPackTo(TransactionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = rev(); _o->rev = _e; }
  { auto _e = user(); if (_e) _o->user = _e->str(); }
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = type(); _o->type = _e; }
  { auto _e = upserts(); if (_e) { _o->upserts.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->upserts[_i]) { _e->Get(_i)->UnPackTo(_o->upserts[_i].get(), _resolver); } else { _o->upserts[_i] = std::unique_ptr<nplex::msgs::KeyValueT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->upserts.resize(0); } }
  { auto _e = deletes(); if (_e) { _o->deletes.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->deletes[_i] = _e->Get(_i)->str(); } } else { _o->deletes.resize(0); } }
}

inline ::flatbuffers::Offset<Transaction> Transaction::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTransaction(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Transaction> CreateTransaction(::flatbuffers::FlatBufferBuilder &_fbb, const TransactionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TransactionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _rev = _o->rev;
  auto _user = _o->user.empty() ? 0 : _fbb.CreateString(_o->user);
  auto _timestamp = _o->timestamp;
  auto _type = _o->type;
  auto _upserts = _o->upserts.size() ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::KeyValue>> (_o->upserts.size(), [](size_t i, _VectorArgs *__va) { return CreateKeyValue(*__va->__fbb, __va->__o->upserts[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _deletes = _o->deletes.size() ? _fbb.CreateVectorOfStrings(_o->deletes) : 0;
  return nplex::msgs::CreateTransaction(
      _fbb,
      _rev,
      _user,
      _timestamp,
      _type,
      _upserts,
      _deletes);
}

inline SnapshotT::SnapshotT(const SnapshotT &o)
      : rev(o.rev) {
  transactions.reserve(o.transactions.size());
  for (const auto &transactions_ : o.transactions) { transactions.emplace_back((transactions_) ? new nplex::msgs::TransactionT(*transactions_) : nullptr); }
}

inline SnapshotT &SnapshotT::operator=(SnapshotT o) FLATBUFFERS_NOEXCEPT {
  std::swap(rev, o.rev);
  std::swap(transactions, o.transactions);
  return *this;
}

inline SnapshotT *Snapshot::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<SnapshotT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Snapshot::UnPackTo(SnapshotT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = rev(); _o->rev = _e; }
  { auto _e = transactions(); if (_e) { _o->transactions.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->transactions[_i]) { _e->Get(_i)->UnPackTo(_o->transactions[_i].get(), _resolver); } else { _o->transactions[_i] = std::unique_ptr<nplex::msgs::TransactionT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->transactions.resize(0); } }
}

inline ::flatbuffers::Offset<Snapshot> Snapshot::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSnapshot(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Snapshot> CreateSnapshot(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SnapshotT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _rev = _o->rev;
  auto _transactions = _o->transactions.size() ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::Transaction>> (_o->transactions.size(), [](size_t i, _VectorArgs *__va) { return CreateTransaction(*__va->__fbb, __va->__o->transactions[i].get(), __va->__rehasher); }, &_va ) : 0;
  return nplex::msgs::CreateSnapshot(
      _fbb,
      _rev,
      _transactions);
}

inline CheckT *Check::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<CheckT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Check::UnPackTo(CheckT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = pattern(); if (_e) _o->pattern = _e->str(); }
  { auto _e = mode(); _o->mode = _e; }
}

inline ::flatbuffers::Offset<Check> Check::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CheckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCheck(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Check> CreateCheck(::flatbuffers::FlatBufferBuilder &_fbb, const CheckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CheckT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _pattern = _o->pattern.empty() ? 0 : _fbb.CreateString(_o->pattern);
  auto _mode = _o->mode;
  return nplex::msgs::CreateCheck(
      _fbb,
      _pattern,
      _mode);
}

inline LoginRequestT *LoginRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<LoginRequestT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LoginRequest::UnPackTo(LoginRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = user(); if (_e) _o->user = _e->str(); }
  { auto _e = password(); if (_e) _o->password = _e->str(); }
}

inline ::flatbuffers::Offset<LoginRequest> LoginRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoginRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateLoginRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LoginRequest> CreateLoginRequest(::flatbuffers::FlatBufferBuilder &_fbb, const LoginRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LoginRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cid = _o->cid;
  auto _user = _o->user.empty() ? 0 : _fbb.CreateString(_o->user);
  auto _password = _o->password.empty() ? 0 : _fbb.CreateString(_o->password);
  return nplex::msgs::CreateLoginRequest(
      _fbb,
      _cid,
      _user,
      _password);
}

inline LoginResponseT *LoginResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<LoginResponseT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LoginResponse::UnPackTo(LoginResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = code(); _o->code = _e; }
  { auto _e = session(); if (_e) _o->session = _e->str(); }
  { auto _e = rev0(); _o->rev0 = _e; }
  { auto _e = crev(); _o->crev = _e; }
}

inline ::flatbuffers::Offset<LoginResponse> LoginResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoginResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateLoginResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LoginResponse> CreateLoginResponse(::flatbuffers::FlatBufferBuilder &_fbb, const LoginResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LoginResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cid = _o->cid;
  auto _code = _o->code;
  auto _session = _o->session.empty() ? 0 : _fbb.CreateString(_o->session);
  auto _rev0 = _o->rev0;
  auto _crev = _o->crev;
  return nplex::msgs::CreateLoginResponse(
      _fbb,
      _cid,
      _code,
      _session,
      _rev0,
      _crev);
}

inline PingRequestT *PingRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PingRequestT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PingRequest::UnPackTo(PingRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = payload(); if (_e) _o->payload = _e->str(); }
}

inline ::flatbuffers::Offset<PingRequest> PingRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PingRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePingRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PingRequest> CreatePingRequest(::flatbuffers::FlatBufferBuilder &_fbb, const PingRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PingRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cid = _o->cid;
  auto _payload = _o->payload.empty() ? 0 : _fbb.CreateString(_o->payload);
  return nplex::msgs::CreatePingRequest(
      _fbb,
      _cid,
      _payload);
}

inline PingResponseT *PingResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PingResponseT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PingResponse::UnPackTo(PingResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = crev(); _o->crev = _e; }
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = payload(); if (_e) _o->payload = _e->str(); }
}

inline ::flatbuffers::Offset<PingResponse> PingResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PingResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePingResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PingResponse> CreatePingResponse(::flatbuffers::FlatBufferBuilder &_fbb, const PingResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PingResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _crev = _o->crev;
  auto _cid = _o->cid;
  auto _payload = _o->payload.empty() ? 0 : _fbb.CreateString(_o->payload);
  return nplex::msgs::CreatePingResponse(
      _fbb,
      _crev,
      _cid,
      _payload);
}

inline LoadRequestT *LoadRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<LoadRequestT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LoadRequest::UnPackTo(LoadRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = mode(); _o->mode = _e; }
  { auto _e = rev(); _o->rev = _e; }
}

inline ::flatbuffers::Offset<LoadRequest> LoadRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoadRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateLoadRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LoadRequest> CreateLoadRequest(::flatbuffers::FlatBufferBuilder &_fbb, const LoadRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LoadRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cid = _o->cid;
  auto _mode = _o->mode;
  auto _rev = _o->rev;
  return nplex::msgs::CreateLoadRequest(
      _fbb,
      _cid,
      _mode,
      _rev);
}

inline LoadResponseT::LoadResponseT(const LoadResponseT &o)
      : cid(o.cid),
        crev(o.crev),
        accepted(o.accepted),
        snapshot((o.snapshot) ? new nplex::msgs::SnapshotT(*o.snapshot) : nullptr) {
}

inline LoadResponseT &LoadResponseT::operator=(LoadResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(cid, o.cid);
  std::swap(crev, o.crev);
  std::swap(accepted, o.accepted);
  std::swap(snapshot, o.snapshot);
  return *this;
}

inline LoadResponseT *LoadResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<LoadResponseT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void LoadResponse::UnPackTo(LoadResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = crev(); _o->crev = _e; }
  { auto _e = accepted(); _o->accepted = _e; }
  { auto _e = snapshot(); if (_e) { if(_o->snapshot) { _e->UnPackTo(_o->snapshot.get(), _resolver); } else { _o->snapshot = std::unique_ptr<nplex::msgs::SnapshotT>(_e->UnPack(_resolver)); } } else if (_o->snapshot) { _o->snapshot.reset(); } }
}

inline ::flatbuffers::Offset<LoadResponse> LoadResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LoadResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateLoadResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<LoadResponse> CreateLoadResponse(::flatbuffers::FlatBufferBuilder &_fbb, const LoadResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LoadResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cid = _o->cid;
  auto _crev = _o->crev;
  auto _accepted = _o->accepted;
  auto _snapshot = _o->snapshot ? CreateSnapshot(_fbb, _o->snapshot.get(), _rehasher) : 0;
  return nplex::msgs::CreateLoadResponse(
      _fbb,
      _cid,
      _crev,
      _accepted,
      _snapshot);
}

inline CommitResponseT::CommitResponseT(const CommitResponseT &o)
      : crev(o.crev),
        cid(o.cid),
        transaction((o.transaction) ? new nplex::msgs::TransactionT(*o.transaction) : nullptr) {
}

inline CommitResponseT &CommitResponseT::operator=(CommitResponseT o) FLATBUFFERS_NOEXCEPT {
  std::swap(crev, o.crev);
  std::swap(cid, o.cid);
  std::swap(transaction, o.transaction);
  return *this;
}

inline CommitResponseT *CommitResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<CommitResponseT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CommitResponse::UnPackTo(CommitResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = crev(); _o->crev = _e; }
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = transaction(); if (_e) { if(_o->transaction) { _e->UnPackTo(_o->transaction.get(), _resolver); } else { _o->transaction = std::unique_ptr<nplex::msgs::TransactionT>(_e->UnPack(_resolver)); } } else if (_o->transaction) { _o->transaction.reset(); } }
}

inline ::flatbuffers::Offset<CommitResponse> CommitResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommitResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCommitResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CommitResponse> CreateCommitResponse(::flatbuffers::FlatBufferBuilder &_fbb, const CommitResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CommitResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _crev = _o->crev;
  auto _cid = _o->cid;
  auto _transaction = _o->transaction ? CreateTransaction(_fbb, _o->transaction.get(), _rehasher) : 0;
  return nplex::msgs::CreateCommitResponse(
      _fbb,
      _crev,
      _cid,
      _transaction);
}

inline SubmitRequestT::SubmitRequestT(const SubmitRequestT &o)
      : cid(o.cid),
        crev(o.crev),
        type(o.type),
        deletes(o.deletes) {
  upserts.reserve(o.upserts.size());
  for (const auto &upserts_ : o.upserts) { upserts.emplace_back((upserts_) ? new nplex::msgs::KeyValueT(*upserts_) : nullptr); }
  checks.reserve(o.checks.size());
  for (const auto &checks_ : o.checks) { checks.emplace_back((checks_) ? new nplex::msgs::CheckT(*checks_) : nullptr); }
}

inline SubmitRequestT &SubmitRequestT::operator=(SubmitRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(cid, o.cid);
  std::swap(crev, o.crev);
  std::swap(type, o.type);
  std::swap(upserts, o.upserts);
  std::swap(deletes, o.deletes);
  std::swap(checks, o.checks);
  return *this;
}

inline SubmitRequestT *SubmitRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<SubmitRequestT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SubmitRequest::UnPackTo(SubmitRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = crev(); _o->crev = _e; }
  { auto _e = type(); _o->type = _e; }
  { auto _e = upserts(); if (_e) { _o->upserts.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->upserts[_i]) { _e->Get(_i)->UnPackTo(_o->upserts[_i].get(), _resolver); } else { _o->upserts[_i] = std::unique_ptr<nplex::msgs::KeyValueT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->upserts.resize(0); } }
  { auto _e = deletes(); if (_e) { _o->deletes.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->deletes[_i] = _e->Get(_i)->str(); } } else { _o->deletes.resize(0); } }
  { auto _e = checks(); if (_e) { _o->checks.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->checks[_i]) { _e->Get(_i)->UnPackTo(_o->checks[_i].get(), _resolver); } else { _o->checks[_i] = std::unique_ptr<nplex::msgs::CheckT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->checks.resize(0); } }
}

inline ::flatbuffers::Offset<SubmitRequest> SubmitRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSubmitRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SubmitRequest> CreateSubmitRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SubmitRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cid = _o->cid;
  auto _crev = _o->crev;
  auto _type = _o->type;
  auto _upserts = _o->upserts.size() ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::KeyValue>> (_o->upserts.size(), [](size_t i, _VectorArgs *__va) { return CreateKeyValue(*__va->__fbb, __va->__o->upserts[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _deletes = _o->deletes.size() ? _fbb.CreateVectorOfStrings(_o->deletes) : 0;
  auto _checks = _o->checks.size() ? _fbb.CreateVector<::flatbuffers::Offset<nplex::msgs::Check>> (_o->checks.size(), [](size_t i, _VectorArgs *__va) { return CreateCheck(*__va->__fbb, __va->__o->checks[i].get(), __va->__rehasher); }, &_va ) : 0;
  return nplex::msgs::CreateSubmitRequest(
      _fbb,
      _cid,
      _crev,
      _type,
      _upserts,
      _deletes,
      _checks);
}

inline SubmitResponseT *SubmitResponse::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<SubmitResponseT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SubmitResponse::UnPackTo(SubmitResponseT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = cid(); _o->cid = _e; }
  { auto _e = crev(); _o->crev = _e; }
  { auto _e = erev(); _o->erev = _e; }
  { auto _e = error(); if (_e) _o->error = _e->str(); }
}

inline ::flatbuffers::Offset<SubmitResponse> SubmitResponse::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitResponseT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSubmitResponse(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SubmitResponse> CreateSubmitResponse(::flatbuffers::FlatBufferBuilder &_fbb, const SubmitResponseT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SubmitResponseT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _cid = _o->cid;
  auto _crev = _o->crev;
  auto _erev = _o->erev;
  auto _error = _o->error.empty() ? 0 : _fbb.CreateString(_o->error);
  return nplex::msgs::CreateSubmitResponse(
      _fbb,
      _cid,
      _crev,
      _erev,
      _error);
}

inline KeepAliveRequestT *KeepAliveRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<KeepAliveRequestT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void KeepAliveRequest::UnPackTo(KeepAliveRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = crev(); _o->crev = _e; }
}

inline ::flatbuffers::Offset<KeepAliveRequest> KeepAliveRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const KeepAliveRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateKeepAliveRequest(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<KeepAliveRequest> CreateKeepAliveRequest(::flatbuffers::FlatBufferBuilder &_fbb, const KeepAliveRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const KeepAliveRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _crev = _o->crev;
  return nplex::msgs::CreateKeepAliveRequest(
      _fbb,
      _crev);
}

}  // namespace msgs
}  // namespace nplex

#endif  // FLATBUFFERS_GENERATED_MESSAGES_NPLEX_MSGS_H_
